import std/tables

let Icons* = {
  "ext": {
    ".go":    "󰟓",
    ".py":    "󰌠",
    ".conf":  "",
    ".toml":  "",
    ".yaml":  "",
    ".jpg":   "",
    ".png":   "",
    ".scm":   "",
    ".html":  "",
    ".css":   "󰌜",
    ".js":    "",
    ".ts":    "",
    ".nim":   "",
    ".md":    "󰍔",
    ".cpp":   "󰙲",
    ".c":     "󰙱",
    ".ipynb": "",
    ".json":  "",
    ".csv":   "",
    ".txt":   "",
    ".jsx":   "",
    ".tsx":   "",
    ".pdf":   "",
    ".tar":   "",
    ".zip":   "",
    ".rar":   "",
    ".docx":  "",
    ".doc":   "",
    ".org":   "",
    ".rs":    "",
    ".svg":   "",
    ".mp4":   "",

  }.toTable(),

  "name": {
    "Dockerfile": "",
    "README":     "󰍔",
    "LICENSE":    "",
  }.toTable(),

  "directories": {
    "node_modules": "",
    "Videos":       "",
    "Documents":    "",
    "Downloads":    "󰇚",
    "Music":        "󰝚",
    "Desktop":      "",
    "src":          "󱃖",
    "bin":          "󰴉",
    "config":       "󱁿",
    "configs":      "󱁿",
    "conf":         "󱁿",
    "assets":       "󱞊",
    ".git":         "",
  }.toTable(),

  "other": {
    "directory":  "",
    "executable": "",
    "plainFile":  "",
  }.toTable(),
}.toTable()
