import std/tables

let Icons* = {
  "ext": {
    ".astro":   "",
    ".c":       "󰙱",
    ".clj":     "",
    ".conf":    "",
    ".cfg":     "",
    ".cpp":     "󰙲",
    ".cs":      "󰌛",
    ".css":     "󰌜",
    ".csv":     "",
    ".d":       "",
    ".dart":    "",
    ".doc":     "",
    ".docx":    "",
    ".elm":     "",
    ".go":      "󰟓",
    ".haskell": "",
    ".html":    "",
    ".ipynb":   "",
    ".java":    "",
    ".jl":      "",
    ".jpg":     "",
    ".js":      "",
    ".json":    "",
    ".jsx":     "",
    ".kt":      "",
    ".lua":     "",
    ".m":       "",
    ".mat":     "",
    ".md":      "󰍔",
    ".mp4":     "",
    ".nim":     "",
    ".nimble":  "",
    ".org":     "",
    ".pdf":     "",
    ".php":     "󰌟",
    ".pl":      "",
    ".png":     "",
    ".py":      "󰌠",
    ".r":       "󰟔",
    ".rar":     "",
    ".rb":      "󰴭",
    ".rs":      "󱘗",
    ".scala":   "",
    ".scm":     "",
    ".scss":    "",
    ".sh":      "",
    ".sqlite":  "",
    ".svelte":  "",
    ".svg":     "",
    ".swift":   "󰛥",
    ".tar":     "",
    ".tex":     "",
    ".toml":    "",
    ".ts":      "",
    ".tsx":     "",
    ".tsx":     "",
    ".txt":     "",
    ".v":       "",
    ".vim":     "",
    ".vue":     "󰡄",
    ".yaml":    "",
    ".zig":     "",
    ".zip":     "",
    ".zsh":     "",
    ".zshrc":   "",
  }.toTable(),

  "name": {
    "Dockerfile": "",
    "README":     "󰍔",
    "LICENSE":    "",
  }.toTable(),

  "directories": {
    "node_modules": "",
    "Videos":       "",
    "Documents":    "",
    "Downloads":    "󰇚",
    "Music":        "󰝚",
    "Desktop":      "",
    "docs":         "󱂷",
    "src":          "󱃖",
    "bin":          "󰴉",
    "cache":        "󰪺",
    "tmp":          "󰪺",
    "test":         "󱞊",
    "lib":          "󰲂",
    "config":       "󱁿",
    "configs":      "󱁿",
    "conf":         "󱁿",
    "assets":       "󱞊",
    "local":        "󰉌",
    ".git":         "",
  }.toTable(),

  "other": {
    "directory":  "",
    "executable": "",
    "plainFile":  "",
  }.toTable(),
}.toTable()
